// COLORS

#define PASTEL_PINK         0xFFF5B7C7
#define PASTEL_ORANGE       0xFFFFE4B5
#define PASTEL_YELLOW       0xFFFFFFF0
#define PASTEL_GREEN        0xFFB0E0E6
#define PASTEL_BLUE         0xFFADD8E6
#define PASTEL_PURPLE       0xFFD8BFD8
#define PASTEL_GRAY         0xFFD3D3D3

#define PASTEL_LIGHT_PINK   0xFFF0F0F5
#define PASTEL_LIGHT_ORANGE 0xFFFFF8E7
#define PASTEL_LIGHT_YELLOW 0xFFFFFFFA
#define PASTEL_LIGHT_GREEN  0xFFE0FFFF
#define PASTEL_LIGHT_BLUE   0xFFE0FFFF
#define PASTEL_LIGHT_PURPLE 0xFFF0F0FF
#define PASTEL_LIGHT_GRAY   0xFFF5F5F5

#define PASTEL_DEEP_PINK    0xFFF08080
#define PASTEL_DEEP_ORANGE  0xFFFFA07A
#define PASTEL_DEEP_YELLOW  0xFFFFFFC0
#define PASTEL_DEEP_GREEN   0xFF98FB98
#define PASTEL_DEEP_BLUE    0xFF87CEEB 
#define PASTEL_DEEP_PURPLE  0xFFC71585
#define PASTEL_DEEP_GRAY    0xFFA9A9A9
#define PASTEL_DEEP_BROWN   0xFFA0522D